
INSERT INTO `fx_user` (`user_id`, `org_id`, `user_name`, `user_email`, `user_pass`, `user_role`, `user_phone`, `user_sid`, `user_options`, `user_avatar`, `is_active`, `created_at`) VALUES
('67ecea4c-5ff0-44b5-92c5-bcd86bcf1720-20231216-003205', 'ORG', 'admin.o', '{admin-email}', '{admin-pass}', '1', 'NIL', NULL, NULL, NULL, '1', '2023-12-15 23:32:05');

INSERT INTO `fx_staff` (`user_id`, `org_id`, `role_id`, `employee_id`, `department`, `designation`, `qualification`, `work_exp`, `firstname`, `lastname`, `middlename`, `father_name`, `mother_name`, `phone`, `rfid_code`, `email`, `dob`, `marital_status`, `religion`, `date_of_joining`, `date_of_leaving`, `address`, `note`, `img`, `gender`, `account_title`, `bank_account_no`, `bank_name`, `payscale`, `basic_salary`, `epf_no`, `contract_type`, `shift`, `location`, `facebook`, `twitter`, `linkedin`, `instagram`, `resume`, `joining_letter`, `resignation_letter`, `other_document`, `is_active`, `created_at`, `updated_at`, `disabled_at`) VALUES
('67ecea4c-5ff0-44b5-92c5-bcd86bcf1720-20231216-003205', 'ORG', '1', '1', NULL, NULL, NULL, NULL, 'Admin', 'Operator', NULL, NULL, NULL, 'NIL', NULL, '{admin-email}', '1989-01-01', NULL, NULL, '2023-12-16', NULL, 'NIL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, '2023-12-15 23:32:05', '2023-12-15 23:32:05', NULL);

INSERT INTO `fx_org` (`type_id`, `reg_num`, `name`, `img`, `img_white`, `favicon`, `email`, `phone`, `slogan`, `description`, `website`, `address`, `province`, `county`, `country`, `org_id`, `default_row_per_page`, `default_template`, `default_theme`, `frontend_template`, `frontend_theme`, `license`, `license_package`, `license_start_date`, `license_end_date`, `created_at`, `updated_at`) VALUES
(1, NULL, 'COMPANY NAME', NULL, NULL, NULL, '{admin-email}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ORG', 25, 'default', 'default', 'default', 'default', NULL, 'Free', NULL, NULL, '2023-12-15 23:32:06', '2023-12-15 23:32:06');
